FROM node:12.2.0-alpine

WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY ./server/package*.json ./

RUN npm install

COPY ./server ./

EXPOSE 5000

CMD ["npm", "run", "server"]
